[package]
name = "mtf"
version = "0.1.0"
authors = ["Robin Ole Heinemann <robin.ole.heinemann@t-online.de>"]
edition = "2018"

[dependencies]
memmap = "*"
jetscii = "*"
byteorder = "*"
bitflags = "*"
failure = "*"
